### PR TITLE
Establish relationships to easily access transaction and block information from inputs and outputs

### PR DESCRIPTION
**Pull request by rhyslbw**
Supersedes #195 (Thanks @mebassett)

Includes:
- input -> transaction
- input -> source transaction (where it was an output)
- output -> transaction

**_and_** expressions to use in filtering and sorting.

### CODE REVIEW

**Comment by mebassett** [comment]
After building the hasura docker image, starting hasura, and building and starting the node application (with `yarn && yarn build` followed by `cd dist/; HASURA_URI=... node index.js`), I try running

```
$ curl -X POST -H "Content-Type: application/json" -d '{"query": "{ cardano { blockHeight }}"}' http://localhost:3100/graphql
```

Alas, I get the following error:
```
{"errors":[{"message":"Cannot return null for non-nullable field Query.cardano.","locations":[{"line":1,"column":3}],"path":["cardano"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Error: Cannot return null for non-nullable field Query.cardano.","    at completeValue (/home/mebassett/Documents/cardano-graphql/node_modules/graphql/execution/execute.js:560:13)","    at /home/mebassett/Documents/cardano-graphql/node_modules/graphql/execution/execute.js:492:16","    at processTicksAndRejections (internal/process/task_queues.js:97:5)","    at async Promise.all (index 0)"]}}}],"data":null}
```

I had noticed some errors yesterday, but I thought it was a corrupt database state.  Today I re-stored everything and re-build with #195 and with master.  Neither of them had any issues.

**Comment by rhyslbw** [comment]
@mebassett That error is a product of db-sync not being at the chain tip during the initial sync. Was this the conditions when running the query?

**Comment by nicarq** [comment]
@rhyslbw it's working for me 👌

**Comment by rhyslbw** [comment]
Re-implemented in #201, as it was easier than reconciling the master branch changes

**Pull request closed without merging**
