### PR TITLE
Change Transaction Fee from BigInt! -> String!

### PR DESCRIPTION
**Pull request by oneEdoubleD**
This fixes a backwards compatibility issue where Transaction Fee used to be a string but in GraphQL was set to be a BigInt!. Changing this to String means it passes our data parity tests.

### CODE REVIEW

**Comment by ArturWieczorek** [comment]
Quick question about `transactionsCount` field @rhyslbw , should it be of type `String` or `Integer` ?
In Explorer it's a number. Details below.

**Current Explorer**: 
Example query: https://explorer.cardano.org/api-new/epochs/0/3313
Field output: "cbeTxNum":1


VS

**graphQL**: 

Example query: https://cardano-graphql-mainnet.daedalus-operations.com/
```
query EpochDetails{
epochs(where: {number:{_eq:0}}){
  number
     blocks (where: {slotWithinEpoch:{_eq:3313}}){  
      id
      transactionsCount
      size
      fees
    }
}
}
```
Field output:"transactionsCount": "1"

**Comment by oneEdoubleD** [comment]
@ArturWieczorek It should be a number for backwards compatibility - I checked with Alex.

**Comment by rhyslbw** [comment]
The model of being able to aggregate across the whole chain can return some very large numbers, and I've tried to be consistent and present these values in the same way. In this case it's already a write-time calculated value, not a currency field like ADA, but is possible to be used in aggregation query across the whole chain https://github.com/input-output-hk/cardano-graphql/blob/master/src/schema.graphql#L282

**Comment by KtorZ** [comment]
What? What.. wait.. no !

If your test is expecting this to be a string @oneEdoubleD , I will definitely argue that your test is **wrong**.  Expecting data-type parity between graphQL and the legacy "REST" monster API is really not something we want. We do actually want the opposite in most cases! 

This API was an abomination and, if we are forced to keep it as-is for backward compatibility reasons, we **should not** propagate those atrocities to the new components that are following a design that is actually sound. 

`fee` here ought to be a number, not a string. Can we revert that please?

**Comment by oneEdoubleD** [comment]
To summarise a conversation between @KtorZ, Alex, and myself:

> So to summarise, for GraphQL we are okay with breaking changes but all the data available through the RestAPI should be obtainable through GQL too?

Therefore I will submit a PR to revert this change and update the CI tests accordingly.

**Pull request merged**
